version: '3.8'
services:
  postgresql:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./packages/messages/schema.sql:/docker-entrypoint-initdb.d/02_schema.sql

  localstack:
    image: localstack/localstack:2.3.2
    ports:
      - 4566:4566
    environment:
      SERVICES: "s3,secretsmanager"
      DATA_DIR: "/tmp/localstack/data"
      FILES_S3_BUCKET: "life-events-files"
      IMAGES_S3_BUCKET: "life-events-images"
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh' # ready hook
  scheduler:
    image: scheduler-api-container:latest
    build:
      context: .
      dockerfile: ./apps/scheduler-api/Dockerfile
    ports:
      - 8004:8004
    env_file:
      - './apps/scheduler-api/.env'
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
volumes:
  db:
    driver: local
